quarkus.hibernate-orm.dialect: org.hibernate.dialect.PostgreSQL95Dialect
quarkus.hibernate-orm.log.sql: true

quarkus:
  application:
    name: Quarkus Sample
  
  http:
    port: 8080
    cors:
      ~: true
      methods: GET,POST,PUT,DELETE,OPTIONS

  resteasy:
    path: /api

# configure your datasource
  datasource:
    db-kind: postgresql

# quarkus.datasource.driver=org.postgresql.Driver
    jdbc:
      url: jdbc:postgresql://localhost:5432/productdb
      detect-statement-leaks: false
    username: user
    password: superSecret
    
# hibernate
  hibernate-orm:
    database.generation: validate
    database.generation.halt-on-error: true
    database:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect

# jackson
  jackson:
    write-dates-as-timestamps: true 
    fail-on-unknown-properties: true

# liquibase
  # liquibase:
    # migrate-at-start: true